- pages/concepts/validator-network/validator-types-and-states.mdx
> add note about min cfe version

- pages/integration/liquidity-provision/lp-api.mdx
Based on feedback from an MM, added some examples and clarification of encoding types.
> update lp rpc page

- pages/integration/liquidity-provision/lp-api.mdx
- pages/integration/swapping-and-aggregation/running-a-broker/broker-api.mdx
Lots of changes that I was working on for #61 but it got merged before I finished. 
- Fixes some of the example json. Mostly around the `increase_or_decrease` object.
- Many other small fixes/updates and cleanup
> Update LP and broker API docs

- pages/integration/swapping-and-aggregation/javascript-sdk/swap-assets/execute-swap.mdx
- pages/integration/swapping-and-aggregation/javascript-sdk/swap-assets/request-deposit-address.mdx
[WEB-499]
Adding message size limitation to JS SDK:
- Request deposit address
- Execute swap
> update message size in js sdk swap pages

- pages/concepts/swaps-amm/_meta.json
- pages/concepts/swaps-amm/cross-chain-messaging.mdx
- pages/integration/swapping-and-aggregation/cross-chain-messaging.mdx
Adding an introductory cross-chain messaging page in "Concepts".
> chore: add ccm concept

- pages/integration/liquidity-provision/lp-rpcs.mdx
Update the information of block confirmation for LPs.
> update block confirmation information

- pages/mainnet/validator-setup/funding-and-bidding.mdx
> Spelling funding-and-bidding.mdx

- pages/mainnet/validator-setup/prerequisites.mdx
> Spelling prerequisites.mdx

- pages/integration/swapping-and-aggregation/evm-integration/vault-swaps.mdx
- pages/integration/swapping-and-aggregation/supported-chains-and-assets.mdx
- Add mainnet EVM contract addresses
- Fix typo
> chore: add mainnet evm contract addresses

- pages/integration/swapping-and-aggregation/javascript-sdk/get-status.mdx
[WEB-698]
Add ccmMessage to getStatus in sdk
> [WEB-698] Add ccmMessage to getStatus in sdk

- pages/integration/liquidity-provision/lp-api.mdx
> doc: order_fills rpc

- pages/integration/liquidity-provision/lp-rpcs.mdx
For this feature: https://github.com/chainflip-io/chainflip-backend/pull/4269
> doc: cf_pool_orderbook

- pages/integration/liquidity-provision/lp-rpcs.mdx
Added docs for PR: https://github.com/chainflip-io/chainflip-backend/pull/4401.
> docs: :memo: added docs for cf_asset_balances

- pages/integration/swapping-and-aggregation/running-a-broker/broker-api.mdx
Added comment on how to install the broker api
> Added comment on how to install the broker api

- README.md
- pages/integration/liquidity-provision/lp-api.mdx
Added documentation for the `lp_request_redemption` RPC that was added to the LP API in [#4292](https://github.com/chainflip-io/chainflip-backend/pull/4292)
> Added `lp_request_redemption` to lp api

- pages/integration/swapping-and-aggregation/javascript-sdk/get-assets.mdx
- pages/integration/swapping-and-aggregation/javascript-sdk/get-chains.mdx
- pages/integration/swapping-and-aggregation/javascript-sdk/get-quote.mdx
- pages/integration/swapping-and-aggregation/javascript-sdk/get-status.mdx
- pages/integration/swapping-and-aggregation/javascript-sdk/quick-start.mdx
- pages/integration/swapping-and-aggregation/javascript-sdk/swap-assets/request-deposit-address.mdx
- styles/globals.css
> add optional/required labels to method argument documentation [WEB-520]

- pages/mainnet/validator-setup/important-notes.mdx
This is how this part currently looks, I am hoping by quoting the $FLIP it will render correctly
> fix: formatting error due to $

- pages/swapping/integrations/quick-start.mdx
- pages/swapping/integrations/running-a-broker/affiliate-brokers.mdx
Provide the swapping quick start flow as well as some extra info on why an broker api provider can be useful
> Swapping quick start

- pages/swapping/integrations/advanced/vault-swaps.mdx
- pages/swapping/integrations/javascript-sdk/swap-assets/request-deposit-address.mdx
- pages/validators/misc/changelog.mdx
https://english.stackexchange.com/questions/3640/is-substract-versus-subtract-a-proper-word
> Fix "Substract" typos

- pages/swapping/integrations/advanced/cross-chain-messaging/cross-chain-messaging.mdx
- pages/swapping/swapping-basics.mdx
Added a short description of DCA including how behavies with FoK and CCM. I think only the SDK part is missing?
> docs: dca first draft

- pages/lp/integrations/lp-rpcs.mdx
Caused some confusion here: https://discord.com/channels/824147014140952596/1290895280077672491/1291584695313891329
> fix: request_id -> swap_request_id in example

- pages/swapping/integrations/running-a-broker/broker-api.mdx
Update `gas_budget` type to hex string.
> chore: update gas budget

- pages/lp/integrations/lp-api.mdx
> mark lp_asset_balances as deprecated

- pages/swapping/integrations/running-a-broker/broker-api.mdx
> feat: Add documentation for new broker-level-screening related methods of broker API

- next-env.d.ts
- pages/swapping/integrations/chainflip-account/creating.mdx
- pages/validators/mainnet/validator-setup/keys.mdx
- pages/validators/testnet/validator-setup/keys.mdx
- Move file permission changes before the final checks so the final check output matches the final expected outcome
- We now have validator gas refunds, so docs updated to reflect that
> Update validator docs

- pages/swapping/supported-chains-and-assets.mdx
Adding `mainnet` tag to Chains Solana and Assets SOL and USDC (SPL-token)
https://docs.chainflip.io/swapping/supported-chains-and-assets#chainflip-networks
> Solana now live on mainnet

- pages/swapping/integrations/advanced/cross-chain-messaging/evm-ccm.mdx
In #465 I managed to introduce a typo while adding two words :sweat:
> chore: fix typo

- pages/concepts/token-economics/incentive-design-emission-and-burning.mdx
Please double check that the link actually works on devleopment.
I can't test it because I'm editing this directly from Github file editor.
> docs: Fix broken link

- pages/swapping/integrations/advanced/cross-chain-messaging/sol-ccm.mdx
- pages/swapping/integrations/advanced/vault-swaps/bitcoin.mdx
- pages/swapping/integrations/advanced/vault-swaps/evm.mdx
- pages/swapping/integrations/advanced/vault-swaps/solana.mdx
- pages/swapping/integrations/running-a-broker/broker-api.mdx
Follow up from: https://github.com/chainflip-io/chainflip-docs/pull/528#discussion_r1998327532
> chore: update broker api endpoints in examples

- pages/swapping/integrations/advanced/vault-swaps/encoding-reference.mdx
- pages/validators/mainnet/validator-setup/engine-settings.mdx
- pages/validators/testnet/validator-setup/engine-settings.mdx
Probably not complete, but here are some important ones.
> chore: add assethub docs

- pages/swapping/integrations/advanced/cross-chain-messaging/cross-chain-messaging.mdx
- pages/swapping/integrations/advanced/cross-chain-messaging/evm-ccm.mdx
- pages/swapping/integrations/advanced/cross-chain-messaging/sol-ccm.mdx
- pages/swapping/integrations/javascript-sdk/get-quote-v2.mdx
- pages/swapping/integrations/javascript-sdk/quick-start.mdx
> docs: improve CCM gas budget and CCM estimations docs

- pages/swapping/integrations/javascript-sdk/deprecated/get-status-v1.mdx
should be merged after sdk has been released
> chore: add refund fee in SwapFee types

- next-env.d.ts
- pages/lp/integrations/lp-api.mdx
> LP-API: added close_order_at field
